# ----------------------------------------------------------------------------------------------------------------------
# Profile
# ----------------------------------------------------------------------------------------------------------------------
name = "Ash's Pikachu"
photo = "https://i.imgur.com/sohWhy9.jpg"

email = "piik@you.uwu"
phone = "+1 PIK ACH UUUU"
birthday = '2018-06-01'
address = 'Somewhere in Kanto'

[occupation]
title = "A Beloved Pet"
employer = "Ash Ketchum"

[links.github]
icon = "http://cdn.onlinewebfonts.com/svg/download_174253.svg"
name = "Species"
text = "Pikachu"
href = "https://en.wikipedia.org/wiki/Pikachu"

[about]
1 = "Piiiiiiika..."
2 = [
    "Pika pi?",
    "Pika! Pika pika!",
]


# ----------------------------------------------------------------------------------------------------------------------
# Education
# ----------------------------------------------------------------------------------------------------------------------
[[education]]
date   = {from = "1997", to = "2020"}
school = "Professor Oak's Lab"
degree = "Ash's Pokemon"
info   = "Trained under Ash Ketchum to become the best Pikachu around."


# ----------------------------------------------------------------------------------------------------------------------
# Skills
# ----------------------------------------------------------------------------------------------------------------------
[[skills]]
icon = "web_design"
name = "Web Design"
points = ['HTML', 'CSS']
