# ----------------------------------------------------------------------------------------------------------------------
# Profile
# ----------------------------------------------------------------------------------------------------------------------
name = "Ash's Pikachu"
photo = "https://i.imgur.com/sohWhy9.jpg"

email = "piik@ach.uuu"
phone = "+1 PIK ACH UUUU"
birthday = '2018-06-01'
address = 'Somewhere in Kanto'

[occupation]
title = "A Beloved Pet"
employer = "Ash Ketchum"

[links.pokedex]
icon = "asset:tech_cmake"
name = "Species"
text = "Pikachu"
href = "https://en.wikipedia.org/wiki/Pikachu"

[about]
1 = "Piiiiiiika..."
2 = [
    "Pika pi?",
    "Pika! Pika pika!",
]


# ----------------------------------------------------------------------------------------------------------------------
# Education
# ----------------------------------------------------------------------------------------------------------------------
[[education]]
date   = {from = "1997", to = "2020"}
school = "Professor Oak's Lab"
degree = "Ash's Pokemon"
info   = "Trained under Ash Ketchum to become the best Pikachu around."


# ----------------------------------------------------------------------------------------------------------------------
# Experience
# ----------------------------------------------------------------------------------------------------------------------
[[experience]]
date     = 1997
title    = "Saved The World"
info     = "Saved the world from Team Rocket's evil deeds!"

[[experience]]
date     = 1998
title    = "Saved The World... Again"
info     = "Piiiiiiiika!"


# ----------------------------------------------------------------------------------------------------------------------
# Skills
# ----------------------------------------------------------------------------------------------------------------------
[skill-categories]
moves = "Moves"
items = { name = "Items", minimized = true }

[[skills.moves]]
icon = "asset:tech_gradle"
name = "Thunderbolt"
rating = 4.5
points = ['Paralyzes']

[[skills.moves]]
icon = "asset:icon_user"
name = "Tackle"
rating = 2.3
points = ['Cannot affect Ghost types.']

[[skills.items]]
name = "Potion"

[[skills.items]]
name = "Choice Specs"

[[skills.items]]
name = "Rare Candy"

[[skills.items]]
name = "Pokeball"


# ----------------------------------------------------------------------------------------------------------------------
# Projects
# ----------------------------------------------------------------------------------------------------------------------
[[projects]]
name = "Team Rocket Takedown"
date = "1997"
href = "https://en.wikipedia.org/wiki/Pikachu"
tech = ["Bash"]
info = "I took down Team Rocket yet again!"
# tech-icon = false  # Don't try to use icons instead of tech names.
